# Generated by Django 4.0.4 on 2022-05-10 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptc_proof', models.FileField(null=True, upload_to='proofs')),
                ('graduate_proof', models.FileField(null=True, upload_to='proofs')),
                ('teaching_proof', models.FileField(null=True, upload_to='proofs')),
                ('knowledge_proof', models.FileField(null=True, upload_to='proofs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
