# Generated by Django 4.0.4 on 2022-05-12 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archivist', '0002_alter_proofarchive_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofarchive',
            name='id',
        ),
        migrations.AlterField(
            model_name='proofarchive',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
